### ISSUE TITLE
HHVM + ZeroMQ

### ISSUE THREAD

**Issue by no1youknowz** [greenlion/swanhart-tools#116]
Hey,

Couple of questions.

- Has this been tested with HHVM?  
- I assume this is not an extension it's straight PHP code?
- Why is gearman being used?  Can zeroMQ be used instead?

Thanks

**Comment by greenlion** [comment]
I have not tested with HHVM.  There is not much reason for it, as processing SQL is the most expensive part of Shard-Query and it isn't very expensive.  This is straight code, the Net_Gearman client is included and pure PHP.  Gearman is used because it is easy to set up, supports calling code directly from MySQL (so the proxy and stored procedure interfaces can communicate with the Gearman UDF), to prevent the cluster from being overloaded, and it is highly available.  

The gearman portions of Shard-Query are not pluggable.  You would need to:
a) create workers for zero-mq that implement the same logic as the gearman workers (there are three main workers of varying complexity)
b) modify Shard-Query to use the zero-mq server instead of gearman

Given the complexity, and gearman's simplicity, it seems hardly worth replacing gearman with zeromq.
